#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

DOCKER_REPO_CONF="/etc/apt/sources.list.d/docker.list"

case "$1" in
    purge|remove)

        if [ -e "${DOCKER_REPO_CONF}" ]; then
            rm -f ${DOCKER_REPO_CONF}
        fi

    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
